#!/usr/bin/env bash

#this will pull out required packages for enkf-c via apt
sudo apt-get -y update
#sudo apt-get -y upgrade
sudo apt-get -y install python-dev python-pip python3-dev python3-pip #python
sudo apt-get -y install gcc openmpi-bin openmpi-common libopenmpi-dev libopenmpi1.10 #gcc,mpicc
sudo apt-get -y autoremove
